name: Code format

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    format-check:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x"

            - name: Restore JetBrains tools
              run: dotnet tool restore

            - name: Run Rider formatter
              run:
                dotnet tool run jb cleanupcode UnityTemplateURP.sln --profile="Built-in: Reformat Code" --no-build

            - name: Check formatting diff
              shell: cmd
              run: git diff --exit-code -- Assets/_Project/Scripts
